### PR TITLE
Added CUSTOM PORT Feature

### PR DESCRIPTION
**Pull request by E343IO**
# ADDED CUSTOM PORT FEATURE

Edited : @htr-tech share your opinion about this.

### CODE REVIEW

**Review by Ketns213 — CHANGES_REQUESTED** [review]
zphisher.sh

**Comment by E343IO** [comment]
> zphisher.sh

##### I don't know what you mean to say... but
##### You can download Custom port zphisher :
***
### [Download Custom Port zphisher](https://raw.githubusercontent.com/htr-tech/zphisher/33ced5e11cba482b79def84f86739e72f35221a0/zphisher.sh)
***
##### Hope you like it.
#### commands for termux
```bash
mv -f /sdcard/Download/zphisher.sh <path_to_zphisher_dir>
cd  <path_to_zphisher_dir>
bash zphisher.sh
```
#### non termux users know well how to do.

**Comment by htr-tech** [comment]
seems nice.. will merge after few testing 👀

**Review by htr-tech — APPROVED** [review]

**Comment by E343IO** [comment]
> seems nice.. will merge after few testing 👀

Would you like to add more features?

**Comment by htr-tech** [comment]
> Would you like to add more features?

YES ! I have but currently stuck due to exams 😅 

> BITB , More Templates , Auto Update etc etc..

**Comment by E343IO** [comment]
> 

#### Will go for auto update first.
#### And mail me ur dm id for discussion, that not should be public.
**```business.drk7.mr.m0erek@gmail.com```**

**Pull request merged**
