### PR TITLE
Added URL Masking/ Custom URL - feature

### PR DESCRIPTION
**Pull request by E343IO**

### CODE REVIEW

**Comment by E343IO** [comment]
***Well 😅 4 commits not should be there anyway i update my branch from yours, before PR.
Check history***

**Comment by htr-tech** [comment]
I had written a few lines earlier..That's why i took some of your codes & implemented them on #621 

Will be better if you take a look & suggest..I'll add Color codes later

**Comment by E343IO** [comment]
> I had written a few lines earlier..That's why i took some of your codes & implemented them on #621
> 
> Will be better if you take a look & suggest..I'll add Color codes later

As you wish !!
Its open source dude.

**Comment by E343IO** [comment]
> I had written a few lines earlier..That's why i took some of your codes & implemented them on #621
> 
> Will be better if you take a look & suggest..I'll add Color codes later

Great buddy perfect!! I just forgot put some line
Of url generats by portforwarders, u had did such a great then y u didn't put eairler, well also thx to improving my shell scripting😁

**Comment by E343IO** [comment]
So i'm closing my pr okay?

**Pull request closed without merging**
