### PR TITLE
Create Kawayan

### PR DESCRIPTION
**Pull request by phkawayan**

### CODE REVIEW

**Comment by prem2904** [comment]
Screenshot_2021-07-02-14-41-26-097_org telegram messenger
Hi sir i want command for this

**Comment by Fkkhankhan** [comment]
Plz commands  sir

**Comment by phkawayan** [comment]
I Don't have command for that

**Comment by Fkkhankhan** [comment]
Ok

**Comment by prem2904** [comment]
@phkawayan how can I contact.. To tahmid rayat.... Can you give me his email id or any thing else

**Comment by Fkkhankhan** [comment]
Sir zphisher working no more why and what is the reason???

**Comment by phkawayan** [comment]
You need to on your hotspot if you are using termux, if you are using linux
it's okay.

**Comment by htr-tech** [comment]
> Screenshot_2021-07-02-14-41-26-097_org telegram messenger
> Hi sir i want command for this

there is no such tool of mine 😐

**Comment by prem2904** [comment]
Sir but it's written.... tool created by htr-tech (tahmid rayat)..... 😕😕

**Comment by prem2904** [comment]
Sir can you create a tool to hack rxce..... Like you are free and not working on any other project.... Sir i need it for educational purpose... I'm a YouTuber and my subscribers asked me to make a video on this... But I'm stucked up.... Can you help sir... Please 🙂

**Comment by Faisal8899** [comment]
في سبت، ٣ يوليو، ٢٠٢١ في ٣:٤٩ م، كتب phkawayan ***@***.***>:

**Comment by vickyraja1992** [comment]
Hi

**Pull request closed without merging**
