### PR TITLE
Run ZPhiSher in Docker

### PR DESCRIPTION
**Pull request by MoisesTapia**
All information are in the folder Docker/README.md

- [X] make a image of docker 
- [X] Run zphisher in docker

### CODE REVIEW

**Comment by htr-tech** [comment]
@MoisesTapia  Thanks Bro !

**Comment by htr-tech** [comment]
@MoisesTapia  Bro , My Device got a prblm & the pull was deleted . Please create a new pull request to branch `docker-legacy`

**Comment by MoisesTapia** [comment]
yes !!

**Comment by htr-tech** [comment]
create now plz

**Comment by MoisesTapia** [comment]
Done

**Comment by htr-tech** [comment]
where is the docker file in current  branch `docker-legacy` ?? I think u forgot !

**Comment by MoisesTapia** [comment]
I add the files but I don't know why they don't appear in the branch

**Comment by htr-tech** [comment]
ok no prblm . I will manually upload this . ! thanks for contribution !!

**Pull request merged**
