### PR TITLE
Custom URL Masking

### PR DESCRIPTION
**Pull request by htr-tech**

### CODE REVIEW

**Comment by E343IO** [comment]
LINE : 
https://github.com/htr-tech/zphisher/blob/1c1592bf74ad7219ae952e21bd7a576344df3dd9/zphisher.sh#L599

I suggest put it as :
`=~ ^([w][w][w]|[h][t][t][p][s])$` where `?` is not to imp 
But wait... 
Also u put `${mask://*} =~ (www|https?)` 
thats not be true becoz it only extract's http|s one Instead of using that, use below one 

```bash 
if [[ {$mask_url://*} =~ ^([h][t][t][p][s]|[h][t][t][p])$ || ${mask_url::1} =~ ^([w][w][w])$  ]]; then
 ```

**Comment by htr-tech** [comment]
```
if [[ {$mask_url://*} =~ ^([h][t][t][p][s]|[h][t][t][p])$ || ${mask_url::1} =~ ^([w][w][w])$  ]]; then
```
**Shows the URLs wrong**
sugg
  -  `${mask_url::1}` - Doesn't that print only the first letter of the string ?  It should be `${mask_url::3}`
> thats not be true becoz it only extract's http|s one Instead of using that, use below one
  - `https?` - means it will match both *http* or *https*

#### Check for https:// or www : `[[ {$x//:*} =~ (https?:\/\/) || ${x::3} == "www" ]]`
  - `(https?:\/\/)` matches **http://** or **https://**
  - `${x::3} == "www"` check the first 3 letters of the string
#### & check for Invalid chars : `[[ ${x#http*//} =~ ^[^,~!@%:\=\#\;\^\*\"\'\|\?+\<\>\(\{\)\}\\/]+$ ]]`
  - `${x#http*//}` - trims the `https://` or `http://`

### Together it will be something like
```bash
if [[ {$x//:*} =~ (https?:\/\/) || ${x::3} == "www" ]] && [[ ${x#http*//} =~ ^[^,~!@%:\=\#\;\^\*\"\'\|\?+\<\>\(\{\)\}\\/]+$ ]]; then
...
```

**It also checks the url patterns correctly**
new

The bash script [a.sh](https://github.com/htr-tech/zphisher/files/9818661/a.sh.txt)

**Comment by E343IO** [comment]
> 

Yep sorry 😅 itz `${x::3}`,

**Comment by E343IO** [comment]
> > 
> 
> Yep sorry 😅 itz `${x::3}`,

I was going too fast while explaining you, so some mistakes of mine can handle by @htr-tech

**Comment by E343IO** [comment]
##### Hey there,
##### Check some mistakes :

##### 1st i did :  `{$mask_url//:*}` , and from ur code in [*a.sh*](https://github.com/htr-tech/zphisher/files/9818661/a.sh.txt) coded as `{$mask_url://*}` the term we confuse is `//:*` check stackoverflow [*here*](https://stackoverflow.com/questions/73415180/how-to-extract-protocols-https-to-check-url-using-shell-script)
I'd edit my last comment code please
check once, [*here*](https://github.com/htr-tech/zphisher/pull/621#issuecomment-1283038809) and i apologise for my minor mistakes too.

#### Now check some below pics were you got it easily 
Thx for your support 
Imgs : 

##### Thanks for your effort :
🙃

**Comment by htr-tech** [comment]
- 1 : Why we are not using `${x::3} == "www"`  instead of regular expression for `www` ?
Cause the output we expect is only `www` , Just wanna keep the code as simple as possible :')

- 2 : is there any difference between `^([h][t][t][p][s]|[h][t][t][p])$` & `^([h][t][t][p][s]?)$` ?
   cause `?` will match for both outputs. (source : [stack](https://stackoverflow.com/questions/5583579/question-marks-in-regular-expressions#:~:text=The%20usefulness%20of%20%3F%20is%20easy%20enough%20to%20understand.%20If%20you%20wanted%20to%20find%20both%20http%20and%20https%2C%20you%20could%20use%20a%20pattern%20like%20this%3A))

- 3: Typo 👀 Not a big deal tho
image

**Comment by E343IO** [comment]
True bruh !!

**Comment by E343IO** [comment]
🤣 we r discussing from yesterday
For just one line of code😆

**Comment by E343IO** [comment]
> * 1 : Why we are not using `${x::3} == "www"`  instead of regular expression for `www` ?
>   Cause the output we expect is only `www` , Just wanna keep the code as simple as possible :')
> * 2 : is there any difference between `^([h][t][t][p][s]|[h][t][t][p])$` & `^([h][t][t][p][s]?)$` ?
>   cause `?` will match for both outputs. (source : [stack](https://stackoverflow.com/questions/5583579/question-marks-in-regular-expressions#:~:text=The%20usefulness%20of%20%3F%20is%20easy%20enough%20to%20understand.%20If%20you%20wanted%20to%20find%20both%20http%20and%20https%2C%20you%20could%20use%20a%20pattern%20like%20this%3A))
> * 3: Typo 👀 Not a big deal tho
>   image

Also thx for source bruh: now code seems to be simple and short.

**Comment by htr-tech** [comment]
> 🤣 we r discussing from yesterday For just one line of code😆

Typical Me : when there is nothing to do after exam 😆

**Pull request merged**
